### ISSUE TITLE
scIB fails to import: AttributeError: module 'scanpy.plotting.palettes' has no attribute 'godsnot_64'

### ISSUE THREAD

**Issue by scottgigante** [theislab/scib#128]
Installed scIB with `pip install git+https://github.com/theislab/scib@master` but cannot import the module.

```
>>> import scIB
/home/scottgigante/.local/lib/python3.6/site-packages/numba/core/errors.py:149: UserWarning: Insufficiently recent colorama version found. Numba requires colorama >= 0.3.9
  warnings.warn(msg)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/scottgigante/.local/lib/python3.6/site-packages/scIB/__init__.py", line 2, in <module>
    from scIB import preprocessing, integration, metrics, clustering
  File "/home/scottgigante/.local/lib/python3.6/site-packages/scIB/preprocessing.py", line 51, in <module>
    palette=sc.pl.palettes.godsnot_64):
AttributeError: module 'scanpy.plotting.palettes' has no attribute 'godsnot_64'
>>> import scanpy as sc
>>> sc.__version__
'1.5.1'
>>> dir(sc.plotting.palettes)
['Mapping', 'Sequence', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_plot_color_cycle', 'cm', 'colors', 'default_102', 'default_20', 'default_28', 'godsnot_102', 'vega_10', 'vega_10_scanpy', 'vega_20', 'vega_20_scanpy', 'zeileis_28']
```

**Comment by LuckyMD** [comment]
This is strange... 

We are working with a dev version of scanpy 1.4.5, where the godsnot_64 palette still exists. However, I can't find anywhere in the `scIB` module where `godsnot_64` is directly called outside of the jupyter notebooks in `notebooks/data/preprocessing/immune_cells`. Could you check if there is a hardcoded `palette=sc.pl.palettes.godsnot_64` in the stuff you downloaded?

@mumichae this seems to be in your `plot_QC()` function. Anything you can give insight on?

**Comment by LuckyMD** [comment]
Never mind. I just noticed I had already removed this from my local version of the code and not committed yet. Now it's fixed.
